spring:
  datasource:
    url: jdbc:mariadb://223.130.155.227:3307/BookTory
    username: booktory
    password: 0625!
    driver-class-name: org.mariadb.jdbc.Driver


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  s3:
    bucket: booktory
    accessKey: cYjcuwyStmYkacVhmiCw
    secretKey: xFxYN8XbNaMzupWs6ilwzvbMW1epgyC6P0ne8tYl

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  websocket:
    endpoint: /ws

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.booktory.booktoryserver.products_shop.config

# security debug
#logging:
#  level:
#    org.springframework.security.web.FilterChainProxy : debug


jasypt:
  encryptor:
    bean: jasyptStringEncryptor


pay:
  rest-api-key: 6154717800758684
  rest-api-secret-key: 8MvUjAnMoc9GFf1eeehC57UBaWOrsBnecINfwJdWwbSEnvAPVcxkS9DI0JrlSg0PJG8ShC8EBziBAq0q

springdoc:
  packages-to-scan: com.booktory.booktoryserver
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

server:
  forward-headers-strategy: FRAMEWORK