spring:
  datasource:
    url: jdbc:mariadb://223.130.155.227:3307/BookTory
    username: booktory
    password: 0625!
    driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  s3:
    bucket: booktory
    accessKey: cYjcuwyStmYkacVhmiCw
    secretKey: xFxYN8XbNaMzupWs6ilwzvbMW1epgyC6P0ne8tYl

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.booktory.booktoryserver.products_shop.config

logging:
  level:
    org.springframework.security.web.FilterChainProxy : debug